//This program allows the user to guess an integer generated by a random number generator.
#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	int guess, number, difference, previousDifference;
	srand(time(NULL)); //ensures a different integer is selected every time the program is run
	number = rand() % 500 + 1;

	cout << "Please enter a guess: ";
	cin >> guess;
	difference = number - guess;
	if (difference < 0)
	{
		cout << "Your guess is higher\n";
	}
	else if (difference > 0)
	{
		cout << "Your guess is lower\n";
	}
	else if (difference == 0)
	{
		cout << "You figured it out!";
		return 0;
	}
	previousDifference = abs(difference);

	for (int tries = 1; tries <= 12; tries++)
	{
		cout << "Please enter a guess: ";
		cin >> guess;
		difference = number - guess;
		difference = abs(difference); //avoids discrepancies with negative differences

		if (guess == number)
		{
			cout << "You figured it out!";
			return 0;
		}
		if (difference > previousDifference)
		{
			cout << "You are getting colder\n";
		}
		else if (difference < previousDifference)
		{
			cout << "You are getting warmer\n";
		}

		previousDifference = difference;
	}
	cout << "The number is: " << number;
	return 0;
}